#!/usr/bin/env python3
"""Create tiny MindSpeed-MM Qwen3.6 SFT probe datasets and configs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def make_text(repeat: int) -> str:
    unit = (
        "请阅读这段沙箱轨迹，并给出简短、稳定、可复核的操作建议。"
        "状态包括任务目标、约束、最近动作、失败原因和下一步候选。"
    )
    return unit * repeat


def write_dataset(path: Path, rows: int, repeat: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for idx in range(rows):
            row = {
                "images": [],
                "messages": [
                    {"role": "user", "content": f"样本 {idx}: {make_text(repeat)}"},
                    {"role": "assistant", "content": "建议先保留关键状态，确认约束，再执行最小可验证动作。"},
                ],
            }
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_config(path: Path, cutoff_len: int, dataset_path: str, cache_dir: str, save_path: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = f"""# Generated by scripts/make_msmm_sft_probe_assets.py
parallel:
  fully_shard_parallel_size: auto
  fsdp_plan:
    apply_modules:
      - model.visual
      - model.visual.blocks.{{*}}
      - model.language_model
      - model.language_model.embed_tokens
      - model.language_model.layers.{{*}}
      - lm_head
    param_dtype: bf16
    reduce_dtype: fp32
  ulysses_parallel_size: 1

data:
  dataset_param:
    dataset_type: huggingface
    attr:
      images: images
      messages: messages
      role_tag: role
      content_tag: content
      user_tag: user
      assistant_tag: assistant
    preprocess_parameters:
      model_name_or_path: &HF_MODEL_LOAD_PATH /models/Qwen3.6-27B
      use_fast_tokenizer: true
      split_special_tokens: false
      image_max_pixels: 262144
      image_min_pixels: 1024
      video_max_pixels: 16384
      video_min_pixels: 0
      video_fps: 2.0
      video_maxlen: 64
    basic_parameters:
      cutoff_len: {cutoff_len}
      template: qwen3_vl_nothink
      enable_thinking: false
      train_on_prompt: false
      mask_history: false
      dataset_dir: /workspace/llin-rl-dpo/datasets
      dataset: {dataset_path}
      cache_dir: {cache_dir}
      overwrite_cache: true
      preprocessing_batch_size: 4
      preprocessing_num_workers: 1
      max_samples: 8
  dataloader_param:
    pin_memory: true
    shuffle: false
    dataloader_mode: sampler
    drop_last: true
    sampler_type: BaseRandomBatchSampler
    num_workers: 0
    collate_param:
      model_name: qwen3vl
      ignore_pad_token_for_loss: true
    enable_preload: false

model:
  model_id: qwen3_5
  model_name_or_path: *HF_MODEL_LOAD_PATH
  trust_remote_code: true
  attn_implementation: flash_attention_2
  freeze:
    - model.visual
  gdn_implementation: triton
  causal_conv1d_implementation: eager

features:
  loss_cfg:
    loss_type: default
    router_aux_loss_coef: 0.0
  recompute: true
  recompute_plan:
    apply_modules:
      - model.visual.blocks.{{*}}
      - model.language_model.layers.{{*}}
  enable_chunk_loss: true
  chunkloss_plan:
    apply_module: lm_head
    chunk_size: 1024
  enable_activation_offload: false

training:
  micro_batch_size: 1
  gradient_accumulation_steps: 1
  seed: 42
  lr: 1.0e-5
  lr_decay_style: cosine
  lr_warmup_ratio: 0.1
  weight_decay: 0
  train_iters: 1
  clip_grad: 0.0
  init_model_with_meta_device: true
  optimizer: adamw
  adam_fused: true
  save_interval: 10000
  no_load_optim: true
  no_load_rng: true
  no_save_optim: true
  no_save_rng: true
  load: /workspace/llin-rl-dpo/checkpoints/msmm-qwen36-27b-dcp
  save: {save_path}
  use_deter_comp: false
  plugin:
    - mindspeed_mm/fsdp/models/qwen3_5
    - mindspeed_mm/fsdp/data/datasets/huggingface

tools:
  profile:
    enable: false
  memory_profile:
    enable: false
"""
    path.write_text(config, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="datasets/msmm_sft_probe_long.jsonl")
    parser.add_argument("--rows", type=int, default=8)
    parser.add_argument("--repeat", type=int, default=520)
    parser.add_argument("--cutoffs", nargs="+", type=int, default=[2048, 4096])
    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    write_dataset(dataset_path, args.rows, args.repeat)
    for cutoff in args.cutoffs:
        write_config(
            Path(f"configs/msmm_qwen36_sft_cutoff{cutoff}_1step.yaml"),
            cutoff,
            f"/workspace/llin-rl-dpo/{dataset_path.as_posix()}",
            f"/workspace/llin-rl-dpo/cache/msmm_sft_cutoff{cutoff}",
            f"/workspace/llin-rl-dpo/outputs/msmm-qwen36-sft-cutoff{cutoff}-1step",
        )
    print(f"wrote dataset={dataset_path} rows={args.rows} cutoffs={args.cutoffs}")


if __name__ == "__main__":
    main()
